# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\export.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_Left = QtWidgets.QVBoxLayout()
        self.verticalLayout_Left.setObjectName("verticalLayout_Left")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_ChooseProtocol = QtWidgets.QLabel(self.centralwidget)
        self.label_ChooseProtocol.setObjectName("label_ChooseProtocol")
        self.gridLayout_2.addWidget(self.label_ChooseProtocol, 2, 0, 1, 1)
        self.comboBox_StartSegment = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_StartSegment.setObjectName("comboBox_StartSegment")
        self.gridLayout_2.addWidget(self.comboBox_StartSegment, 3, 1, 1, 1)
        self.label_EndProtocol = QtWidgets.QLabel(self.centralwidget)
        self.label_EndProtocol.setObjectName("label_EndProtocol")
        self.gridLayout_2.addWidget(self.label_EndProtocol, 4, 0, 1, 1)
        self.comboBox_Protocol = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Protocol.setObjectName("comboBox_Protocol")
        self.gridLayout_2.addWidget(self.comboBox_Protocol, 2, 1, 1, 1)
        self.comboBox_StopSegment = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_StopSegment.setObjectName("comboBox_StopSegment")
        self.gridLayout_2.addWidget(self.comboBox_StopSegment, 4, 1, 1, 1)
        self.label_StartSegment = QtWidgets.QLabel(self.centralwidget)
        self.label_StartSegment.setObjectName("label_StartSegment")
        self.gridLayout_2.addWidget(self.label_StartSegment, 3, 0, 1, 1)
        self.label_SelectionParameters = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SelectionParameters.sizePolicy().hasHeightForWidth())
        self.label_SelectionParameters.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_SelectionParameters.setFont(font)
        self.label_SelectionParameters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_SelectionParameters.setObjectName("label_SelectionParameters")
        self.gridLayout_2.addWidget(self.label_SelectionParameters, 1, 0, 1, 2)
        self.pushButton_Filter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Filter.setObjectName("pushButton_Filter")
        self.gridLayout_2.addWidget(self.pushButton_Filter, 5, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.verticalLayout_Left.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_Left, 0, 0, 1, 1)
        self.verticalLayout_Main = QtWidgets.QVBoxLayout()
        self.verticalLayout_Main.setObjectName("verticalLayout_Main")
        self.label_LabelsFound = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_LabelsFound.setFont(font)
        self.label_LabelsFound.setObjectName("label_LabelsFound")
        self.verticalLayout_Main.addWidget(self.label_LabelsFound)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_Main.addWidget(self.treeView)
        self.gridLayout.addLayout(self.verticalLayout_Main, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Dataset = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_Dataset.setFont(font)
        self.label_Dataset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Dataset.setObjectName("label_Dataset")
        self.verticalLayout.addWidget(self.label_Dataset)
        self.gridLayout_DatasetProperties = QtWidgets.QGridLayout()
        self.gridLayout_DatasetProperties.setObjectName("gridLayout_DatasetProperties")
        self.label_ValidCasesLabel = QtWidgets.QLabel(self.centralwidget)
        self.label_ValidCasesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ValidCasesLabel.setObjectName("label_ValidCasesLabel")
        self.gridLayout_DatasetProperties.addWidget(self.label_ValidCasesLabel, 0, 0, 1, 1)
        self.label_ValidExportsLabel = QtWidgets.QLabel(self.centralwidget)
        self.label_ValidExportsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ValidExportsLabel.setObjectName("label_ValidExportsLabel")
        self.gridLayout_DatasetProperties.addWidget(self.label_ValidExportsLabel, 1, 0, 1, 1)
        self.label_ValidCasesValue = QtWidgets.QLabel(self.centralwidget)
        self.label_ValidCasesValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ValidCasesValue.setObjectName("label_ValidCasesValue")
        self.gridLayout_DatasetProperties.addWidget(self.label_ValidCasesValue, 0, 1, 1, 1)
        self.label_ValidValue = QtWidgets.QLabel(self.centralwidget)
        self.label_ValidValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ValidValue.setObjectName("label_ValidValue")
        self.gridLayout_DatasetProperties.addWidget(self.label_ValidValue, 1, 1, 1, 1)
        self.label_sampleLengthsLabel = QtWidgets.QLabel(self.centralwidget)
        self.label_sampleLengthsLabel.setObjectName("label_sampleLengthsLabel")
        self.gridLayout_DatasetProperties.addWidget(self.label_sampleLengthsLabel, 2, 0, 1, 1)
        self.label_sampleLengthsValue = QtWidgets.QLabel(self.centralwidget)
        self.label_sampleLengthsValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sampleLengthsValue.setObjectName("label_sampleLengthsValue")
        self.gridLayout_DatasetProperties.addWidget(self.label_sampleLengthsValue, 2, 1, 1, 1)
        self.gridLayout_DatasetProperties.setColumnStretch(0, 1)
        self.gridLayout_DatasetProperties.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout_DatasetProperties)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_ExportRange = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ExportRange.setObjectName("comboBox_ExportRange")
        self.gridLayout_4.addWidget(self.comboBox_ExportRange, 0, 1, 1, 1)
        self.pushButton_Export = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Export.sizePolicy().hasHeightForWidth())
        self.pushButton_Export.setSizePolicy(sizePolicy)
        self.pushButton_Export.setObjectName("pushButton_Export")
        self.gridLayout_4.addWidget(self.pushButton_Export, 2, 0, 1, 2)
        self.spinBox_exportBuffer = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_exportBuffer.setObjectName("spinBox_exportBuffer")
        self.gridLayout_4.addWidget(self.spinBox_exportBuffer, 1, 1, 1, 1)
        self.label_ExportRange = QtWidgets.QLabel(self.centralwidget)
        self.label_ExportRange.setObjectName("label_ExportRange")
        self.gridLayout_4.addWidget(self.label_ExportRange, 0, 0, 1, 1)
        self.label_ExportBuffer = QtWidgets.QLabel(self.centralwidget)
        self.label_ExportBuffer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ExportBuffer.setObjectName("label_ExportBuffer")
        self.gridLayout_4.addWidget(self.label_ExportBuffer, 1, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/About.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ChooseProtocol.setText(_translate("MainWindow", "Protocol"))
        self.label_EndProtocol.setText(_translate("MainWindow", "Stop"))
        self.label_StartSegment.setText(_translate("MainWindow", "Start"))
        self.label_SelectionParameters.setText(_translate("MainWindow", "Selection parameters"))
        self.pushButton_Filter.setText(_translate("MainWindow", "Filter"))
        self.label_LabelsFound.setText(_translate("MainWindow", "Labels Found"))
        self.label_Dataset.setText(_translate("MainWindow", "Dataset"))
        self.label_ValidCasesLabel.setText(_translate("MainWindow", "Valid cases"))
        self.label_ValidExportsLabel.setText(_translate("MainWindow", "Valid exports"))
        self.label_ValidCasesValue.setText(_translate("MainWindow", "-"))
        self.label_ValidValue.setText(_translate("MainWindow", "-"))
        self.label_sampleLengthsLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mean length (ms)<br/>(min)<br/>(max)<br/>(SD)<br/>(95%)<br/>(99%)</p></body></html>"))
        self.label_sampleLengthsValue.setText(_translate("MainWindow", "-"))
        self.pushButton_Export.setText(_translate("MainWindow", "Export"))
        self.label_ExportRange.setText(_translate("MainWindow", "Export range"))
        self.label_ExportBuffer.setText(_translate("MainWindow", "<html><head/><body><p>Export buffer<br/>(Pre/post points)</p></body></html>"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

